services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlflow-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./data/mlruns:/app/mlruns
      - ./data/mlartifacts:/app/mlartifacts
