services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlflow-server
    restart: unless-stopped
    ports:
      - "${MLFLOW_HOST_PORT:-80}:5000"
    volumes:
      - ${DATA_ROOT}/mlruns:/app/mlruns
      - ${DATA_ROOT}/mlartifacts:/app/mlartifacts
